jest.mock('fs/promises', () => ({
  readdir: jest.fn(),
  writeFile: jest.fn().mockResolvedValue(undefined),
}));

import { generateManifest } from '@/cli/build';
import { readdir, writeFile } from 'fs/promises';

const mockReaddir = readdir as jest.Mock;
const mockWriteFile = writeFile as jest.Mock;

function file(name: string) {
  return { name, isDirectory: () => false };
}

function dir(name: string) {
  return { name, isDirectory: () => true };
}

const ROUTES = '/fake/routes';

beforeEach(() => {
  mockReaddir.mockResolvedValue([]);
  mockWriteFile.mockResolvedValue(undefined);
});

afterEach(() => {
  jest.clearAllMocks();
});

describe('generateManifest — output file', () => {
  it('writes _manifest.ts inside routesDir', async () => {
    await generateManifest(ROUTES);
    expect(mockWriteFile).toHaveBeenCalledWith(
      `${ROUTES}/_manifest.ts`,
      expect.any(String),
      'utf-8',
    );
  });

  it('includes the auto-generated header comment', async () => {
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain('AUTO-GENERATED by lacis build');
  });

  it('always emits the routes export even when no routes exist', async () => {
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain('export const routes = [');
  });

  it('does not emit import statements when there are no routes', async () => {
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).not.toContain('import *');
  });
});

describe('generateManifest — route discovery', () => {
  it('discovers a root index.ts and maps it to "/"', async () => {
    mockReaddir.mockResolvedValue([file('index.ts')]);
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/'");
    expect(content).toContain("'./index.js'");
  });

  it('discovers a root index.js as well', async () => {
    mockReaddir.mockResolvedValue([file('index.js')]);
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/'");
  });

  it('discovers a nested route and maps directory name to the path segment', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES) return Promise.resolve([dir('users')]);
      if (d.endsWith('/users')) return Promise.resolve([file('index.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/users'");
    expect(content).toContain("'./users/index.js'");
  });

  it('converts [param] directory names to :param route segments', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES) return Promise.resolve([dir('[id]')]);
      if (d.endsWith('/[id]')) return Promise.resolve([file('index.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/:id'");
  });

  it('converts [param?] to :param (optional param syntax)', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES) return Promise.resolve([dir('[slug?]')]);
      if (d.endsWith('/[slug?]')) return Promise.resolve([file('index.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("path: '/:slug'");
  });

  it('discovers multiple routes and imports each with a unique binding', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES) return Promise.resolve([file('index.ts'), dir('api')]);
      if (d.endsWith('/api')) return Promise.resolve([file('index.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain("_route_0");
    expect(content).toContain("_route_1");
  });

  it('skips directories whose names start with "+"', async () => {
    mockReaddir.mockImplementation((d: string) => {
      if (d === ROUTES)
        return Promise.resolve([dir('+layout'), file('index.ts')]);
      return Promise.resolve([]);
    });
    await generateManifest(ROUTES);
    const content: string = mockWriteFile.mock.calls[0][1];
    const routeCount = (content.match(/path:/g) ?? []).length;
    expect(routeCount).toBe(1); // only the root route, not +layout
  });

  it('handles an unreadable routesDir gracefully and still writes an empty manifest', async () => {
    mockReaddir.mockRejectedValue(new Error('ENOENT'));
    await expect(generateManifest(ROUTES)).resolves.toBeUndefined();
    const content: string = mockWriteFile.mock.calls[0][1];
    expect(content).toContain('export const routes = [');
    expect(content).not.toContain('_route_');
  });
});
