import { readdir, writeFile } from 'fs/promises'
import { join, relative } from 'path'

interface DiscoveredRoute {
  importPath: string
  routePath: string
}

async function discoverRoutes(routesDir: string): Promise<DiscoveredRoute[]> {
  const routes: DiscoveredRoute[] = []

  async function scan(dir: string, pathSegments: string[] = []) {
    let entries
    try {
      entries = await readdir(dir, { withFileTypes: true })
    } catch {
      return
    }

    const indexFile = entries.find(
      (e) => !e.isDirectory() && (e.name === 'index.ts' || e.name === 'index.js')
    )

    if (indexFile) {
      const importPath =
        './' + relative(routesDir, join(dir, indexFile.name)).replace(/\\/g, '/').replace(/\.ts$/, '.js')
      const routePath =
        '/' + pathSegments.map((s) => s.replace(/^\[(\w+)\??\]$/, ':$1')).join('/')
      routes.push({ importPath, routePath: routePath === '//' ? '/' : routePath })
    }

    for (const entry of entries) {
      if (entry.isDirectory() && !entry.name.startsWith('+')) {
        await scan(join(dir, entry.name), [...pathSegments, entry.name])
      }
    }
  }

  await scan(routesDir)
  return routes
}

export async function generateManifest(routesDir: string): Promise<void> {
  const routes = await discoverRoutes(routesDir)

  const imports = routes
    .map((r, i) => `import * as _route_${i} from '${r.importPath}'`)
    .join('\n')

  const entries = routes
    .map((r, i) => `  { path: '${r.routePath}', handlers: _route_${i} }`)
    .join(',\n')

  const content = [
    '// AUTO-GENERATED by lacis build — do not edit',
    imports,
    '',
    'export const routes = [',
    entries,
    ']',
    '',
  ].join('\n')

  await writeFile(join(routesDir, '_manifest.ts'), content, 'utf-8')
  console.log(`[lacis] Generated manifest with ${routes.length} route(s)`)
}
