// AUTO-GENERATED by lacis build — do not edit
import * as _route_0 from './index.js'
import * as _route_1 from './echo.js'
import * as _route_2 from './users/[id]/index.js'

export const routes = [
  { path: '/', handlers: _route_0 },
  { path: '/echo', handlers: _route_1 },
  { path: '/users/:id', handlers: _route_2 },
]

export const middlewares = [
]
